# Generated by Django 2.0.3 on 2018-10-11 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
